### PR TITLE
[US1.5] water-level sensor added

### PR DESCRIPTION
**Pull request by ijkeleher**
Water sensor set up to detect water level.

run ```python output.py``` to see data flow in stdout

### CODE REVIEW

**Comment by inci90** [comment]
Nice work

**Comment by auspham** [comment]
`.gitgnore` .hex and binary?

**Review by auspham — CHANGES_REQUESTED** [review]
Binary and Hex should be put in .gitignore

**Comment by ijkeleher** [comment]
@rockmanvnx6 changes made.

**Pull request closed without merging**
